const property = [{
  id: 1,
  owner: 1,
  owner_email: 'user@example.com',
  owner_phone_number: parseFloat('0909879'),
  created_on: Date(),
  state: 'Lagos',
  status: 'sold',
  price: 150000.00,
  city: 'Ibadan',
  address: '2 Bodija Street',
  type: '2 bedroom',
  image_url: 'url',
},
{
  id: 2,
  owner: 2,
  owner_email: 'seyi@example.com',
  owner_phone_number: parseFloat('0909879'),
  created_on: Date(),
  state: 'Lagos',
  status: 'available',
  price: 2000000.00,
  city: 'Ibadan',
  address: '2 Bodija Street',
  type: '3 bedroom',
  image_url: 'url',
},
{
  id: 3,
  owner: 3,
  owner_email: 'tobe@example.com',
  owner_phone_number: parseFloat('0909879'),
  created_on: Date(),
  state: 'Lagos',
  status: 'available',
  price: 150000.00,
  city: 'Ibadan',
  address: '2 Bodija Street',
  type: '1 bedroom',
  image_url: 'url',
},
{
  id: 4,
  owner: 4,
  owner_email: 'glo@example.com',
  owner_phone_number: parseFloat('0909879'),
  created_on: Date(),
  state: 'Lagos',
  status: 'available',
  price: 150000.00,
  city: 'Ibadan',
  address: '2 Bodija Street',
  type: '4 bedroom',
  image_url: 'url',
},
];

export default property;
